name: SDv1.5_fpv
pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
# bbox_mode: 'all-xyz'
# bbox_view_shared: false
crossview_attn_type: basic
train_with_same_noise: false
train_with_same_t: true

runner_module: magicdrive.runner.fpv_video_runner.FPVRunner

pipe_module: magicdrive.pipeline.pipeline_bev_controlnet.StableDiffusionBEVControlNetPipeline

unet_module: magicdrive.networks.unet_2d_condition_fpv.UNet2DConditionModelFPV
use_fp32_for_unet_trainable: true
unet_dir: unet
unet:
  trainable_state: only_new  # only_new or all
  neighboring_view_pair: 
    0: [5, 1]
    1: [0, 2]
    2: [1, 3]
    3: [2, 4]
    4: [3, 5]
    5: [4, 0]
  neighboring_attn_type: add
  zero_module_type: zero_linear
  crossview_attn_type: basic
  img_size: [224, 400]
    
# model_module: diffusers.pipelines.controlnet.multicontrolnet.MultiControlNetModel
controlnets:
  - name: semantic_map
    module: diffusers.models.controlnet.ControlNetModel
  - name: depth
    module: diffusers.models.controlnet.ControlNetModel